# Generated by Django 4.0 on 2021-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='a2rp_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rp_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rp_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rp_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rs_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rs_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rs_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='a2rs_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bad_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bad_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bad_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bad_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bla_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bla_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bla_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='bla_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='blo_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='blo_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='blo_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='blo_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='drc_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='drc_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='drc_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='drc_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='dro_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='dro_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='dro_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='dro_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='fwd_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='fwd_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='fwd_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='fwd_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='pass_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='pass_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='pass_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='pass_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='whi_bytes',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='whi_bytes_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='whi_pckts',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='whi_pckts_ps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
