# Generated by Django 4.0 on 2021-12-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_alter_edge_a2rp_bytes_alter_edge_a2rp_bytes_ps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name_plural': 'blacklist IPs'},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name_plural': 'whitelist IPs'},
        ),
        migrations.AddField(
            model_name='connection',
            name='bps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='pps',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='name',
            field=models.CharField(blank=True, help_text='Display name of edge.', max_length=32, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='edge',
            name='status',
            field=models.BooleanField(default=False, editable=False, verbose_name='Status'),
        ),
    ]
