# Generated by Django 4.0 on 2021-12-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_alter_blacklist_options_alter_whitelist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='a2rp_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rp_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rp_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rp_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rs_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rs_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rs_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='a2rs_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bad_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bad_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bad_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bad_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bla_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bla_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bla_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bla_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='blo_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='blo_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='blo_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='blo_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='drc_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='drc_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='drc_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='drc_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='dro_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='dro_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='dro_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='dro_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='fwd_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='fwd_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='fwd_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='fwd_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='pass_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='pass_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='pass_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='pass_pckts_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='whi_bytes',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='whi_bytes_ps',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='whi_pckts',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='whi_pckts_ps',
        ),
        migrations.AddField(
            model_name='port_punch',
            name='service_ip',
            field=models.CharField(default=0, help_text='Service IP address', max_length=32, verbose_name='Service IP Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port_punch',
            name='service_port',
            field=models.IntegerField(default=0, help_text='Service Port', verbose_name='Service Port'),
        ),
        migrations.CreateModel(
            name='Edge_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField(auto_now=True)),
                ('bla_pckts', models.BigIntegerField(editable=False, null=True)),
                ('bla_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('bla_bytes', models.BigIntegerField(editable=False, null=True)),
                ('bla_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('whi_pckts', models.BigIntegerField(editable=False, null=True)),
                ('whi_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('whi_bytes', models.BigIntegerField(editable=False, null=True)),
                ('whi_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('blo_pckts', models.BigIntegerField(editable=False, null=True)),
                ('blo_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('blo_bytes', models.BigIntegerField(editable=False, null=True)),
                ('blo_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('fwd_pckts', models.BigIntegerField(editable=False, null=True)),
                ('fwd_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('fwd_bytes', models.BigIntegerField(editable=False, null=True)),
                ('fwd_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('fwdo_pckts', models.BigIntegerField(editable=False, null=True)),
                ('fwdo_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('fwdo_bytes', models.BigIntegerField(editable=False, null=True)),
                ('fwdo_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('pass_pckts', models.BigIntegerField(editable=False, null=True)),
                ('pass_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('pass_bytes', models.BigIntegerField(editable=False, null=True)),
                ('pass_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('bad_pckts', models.BigIntegerField(editable=False, null=True)),
                ('bad_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('bad_bytes', models.BigIntegerField(editable=False, null=True)),
                ('bad_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('a2rp_pckts', models.BigIntegerField(editable=False, null=True)),
                ('a2rp_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('a2rp_bytes', models.BigIntegerField(editable=False, null=True)),
                ('a2rp_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('a2rs_pckts', models.BigIntegerField(editable=False, null=True)),
                ('a2rs_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('a2rs_bytes', models.BigIntegerField(editable=False, null=True)),
                ('a2rs_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('dro_pckts', models.BigIntegerField(editable=False, null=True)),
                ('dro_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('dro_bytes', models.BigIntegerField(editable=False, null=True)),
                ('dro_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('drc_pckts', models.BigIntegerField(editable=False, null=True)),
                ('drc_pckts_ps', models.BigIntegerField(editable=False, null=True)),
                ('drc_bytes', models.BigIntegerField(editable=False, null=True)),
                ('drc_bytes_ps', models.BigIntegerField(editable=False, null=True)),
                ('edge_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connections.edge')),
            ],
        ),
        migrations.CreateModel(
            name='Connection_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pps', models.BigIntegerField(editable=False, null=True)),
                ('bps', models.BigIntegerField(editable=False, null=True)),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connections.connection')),
            ],
        ),
    ]
