# Generated by Django 4.0 on 2021-12-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_remove_edge_a2rp_bytes_remove_edge_a2rp_bytes_ps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge_stats',
            name='cpu_load',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
