# Generated by Django 4.0 on 2022-01-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_edge_stats_cpu_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_punch',
            name='dest_ip',
            field=models.CharField(default=0, help_text="The game server machine's IP address", max_length=32, verbose_name='Destination IP Address'),
            preserve_default=False,
        ),
    ]
