# Generated by Django 4.0 on 2022-01-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_port_punch_dest_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='a2s_info_global_cache',
            field=models.BooleanField(default=False, help_text='Whether to enable A2S_INFO global caching.', verbose_name='A2S_INFO Global Cache'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='a2s_info_cache_time',
            field=models.IntegerField(default=45, help_text='A2S_INFO cache time if enabled.', verbose_name='A2S_INFO Cache Time'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='a2s_info_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable A2S_INFO caching.', verbose_name='A2S_INFO Caching'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='bind_port',
            field=models.IntegerField(help_text='Usually the game server port (e.g. 27015).', verbose_name='Bind Port'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='dest_ip',
            field=models.CharField(help_text='The game server machine IP.', max_length=32, verbose_name='Dest IP'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='dest_port',
            field=models.IntegerField(default=0, help_text='Port to translate to (0 = bind port, default).', verbose_name='Dest Port'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable connection.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='filters',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'SRCDS'), (2, 'Rust')], default=0, help_text='Filters to apply for this connection.', verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='icmp_rl_bl',
            field=models.IntegerField(default=0, help_text='ICMP rate limit block time.', verbose_name='ICMP RL BL'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='icmp_rl_bps',
            field=models.IntegerField(default=0, help_text='ICMP rate limit BPS limit.', verbose_name='ICMP RL BPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='icmp_rl_pps',
            field=models.IntegerField(default=0, help_text='ICMP rate limit PPS limit.', verbose_name='ICMP RL PPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='syn_rl_bl',
            field=models.IntegerField(default=0, help_text='TCP SYN rate limit block time.', verbose_name='SYN RL BL'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='syn_rl_bps',
            field=models.IntegerField(default=0, help_text='TCP SYN rate limit BPS limit.', verbose_name='SYN RL BPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='syn_rl_pps',
            field=models.IntegerField(default=0, help_text='TCP SYN rate limit PPS limit.', verbose_name='SYN RL PPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='tcp_rl_bl',
            field=models.IntegerField(default=0, help_text='TCP rate limit block time.', verbose_name='TCP RL BL'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='tcp_rl_bps',
            field=models.IntegerField(default=0, help_text='TCP rate limit BPS limit.', verbose_name='TCP RL BPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='tcp_rl_pps',
            field=models.IntegerField(default=0, help_text='TCP rate limit PPS limit.', verbose_name='TCP RL PPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='udp_rl_bl',
            field=models.IntegerField(default=0, help_text='UDP rate limit block time.', verbose_name='UDP RL BL'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='udp_rl_bps',
            field=models.IntegerField(default=0, help_text='UDP rate limit BPS limit.', verbose_name='UDP RL BPS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='udp_rl_pps',
            field=models.IntegerField(default=0, help_text='UDP rate limit PPS limit.', verbose_name='UDP RL PPS'),
        ),
        migrations.CreateModel(
            name='Connection_A2S_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(help_text='A2S_INFO response text.', max_length=2048, verbose_name='A2S_INFO Response')),
                ('expires', models.BigIntegerField(help_text="Response's expire time in nanoseconds.", null=True, verbose_name='Cache Expire Time')),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connections.connection')),
            ],
        ),
    ]
