# Generated by Django 4.0 on 2022-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_connection_a2s_info_global_cache_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection_a2s_response',
            options={'verbose_name': 'A2S_INFO response', 'verbose_name_plural': 'A2S_INFO responses'},
        ),
        migrations.AddField(
            model_name='connection',
            name='a2s_info_cache_timeout',
            field=models.IntegerField(default=180, help_text='A2S_INFO cache timeout for expired caches.', verbose_name='A2S_INFO Cache Timeout'),
        ),
    ]
