# Generated by Django 4.0 on 2022-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0010_alter_connection_a2s_response_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='protocol',
            field=models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('icmp', 'ICMP')], default='udp', help_text='The protocol for this connection.', max_length=12, verbose_name='Protocol'),
        ),
    ]
