# Generated by Django 4.0 on 2022-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0011_connection_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='bgp',
        ),
        migrations.AddField(
            model_name='edge',
            name='xdp_status',
            field=models.BooleanField(default=False, editable=False, verbose_name='XDP Status'),
        ),
        migrations.AddField(
            model_name='edge_settings',
            name='bgp',
            field=models.BooleanField(default=True, help_text='Whether to enable BGP.', verbose_name='Enable BGP (AKA Announce)'),
        ),
    ]
