# Generated by Django 3.2.10 on 2022-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0012_remove_edge_bgp_edge_xdp_status_edge_settings_bgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validated_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(help_text='The source IP of client.', max_length=32, verbose_name='Source IP')),
                ('src_port', models.IntegerField(default=0, help_text='The source port of client.', verbose_name='Source Port')),
                ('dst_ip', models.CharField(help_text='The destination IP of server.', max_length=32, verbose_name='Destination IP')),
                ('dst_port', models.IntegerField(default=0, help_text='The destination port of server.', verbose_name='Destination Port')),
                ('last_seen', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'validated client',
                'verbose_name_plural': 'validated clients',
            },
        ),
        migrations.AddField(
            model_name='port_punch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='port_punch',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='filters',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'SRCDS'), (2, 'Rust'), (4, 'SRCDS Challenge')], default=0, help_text='Filters to apply for this connection.', verbose_name='Filters'),
        ),
    ]
